/*
 * role-overlay-rest.tf -- Phase 0.H.3
 *
 * Brings up the Confluent REST Proxy (kafka-rest-1). REST Proxy is a Kafka
 * client of the kafka-east cluster (HTTP -> Kafka bridge) and an HTTP client
 * of the Schema Registry HA pair (for Avro/JSON-Schema/Protobuf).
 *
 * Pre-req: role-overlay-ecosystem-tls.tf rendered the PKI keystore on
 * kafka-rest-1; role-overlay-schema-registry.tf brought up the SR pair
 * (REST Proxy's schema.registry.url targets it -- REST starts fine without
 * SR reachable, but Avro ops would fail, so SR-first is the canonical order).
 *
 * Steps:
 *   1. Render /etc/nexus-kafka/kafka-rest.properties on kafka-rest-1.
 *   2. enable + start kafka-rest.service.
 *   3. Wait for https://<ip>:8082/topics to answer + assert it lists the
 *      brokers' topics (proves REST Proxy -> brokers mTLS works).
 *
 * TLS: mTLS to the brokers (client.ssl.* -- the brokers require client
 * certs); the REST listener is HTTPS server-side only
 * (ssl.client.authentication=NONE); REST -> SR validates SR's server cert
 * via schema.registry.ssl.truststore.* (SR's listener is client-auth NONE,
 * so no keystore needed on the SR-client side).
 *
 * Selective ops: var.enable_kafka_rest AND var.enable_kafka_rest_config
 *                AND var.enable_ecosystem_tls.
 */

locals {
  kafka_rest_specs = var.enable_kafka_rest && var.enable_kafka_rest_1 ? [
    { host = "kafka-rest-1", vmnet10 = "192.168.10.88", vmnet11 = "192.168.70.88" }
  ] : []

  # Schema Registry HA-pair URLs over the VMnet10 backplane (REST Proxy's
  # schema.registry.url). Falls back to a localhost placeholder if the SR
  # pair isn't deployed -- REST Proxy still starts; only Avro ops would need
  # a reachable SR.
  kafka_sr_urls = length(local.kafka_sr_specs) > 0 ? join(",", [for n in local.kafka_sr_specs : "https://${n.vmnet10}:8081"]) : "https://localhost:8081"
}

resource "null_resource" "kafka_rest" {
  count = var.enable_kafka_cluster && var.enable_kafka_rest && var.enable_kafka_rest_config && var.enable_ecosystem_tls && length(local.kafka_rest_specs) > 0 ? 1 : 0

  triggers = {
    tls_id        = length(null_resource.kafka_ecosystem_tls) > 0 ? null_resource.kafka_ecosystem_tls[0].id : "disabled"
    sr_id         = length(null_resource.kafka_schema_registry) > 0 ? null_resource.kafka_schema_registry[0].id : "disabled"
    bootstrap     = local.kafka_east_bootstrap
    sr_urls       = local.kafka_sr_urls
    rest_config_v = "1" # v1 = original. mTLS to brokers (client.ssl.*), HTTPS listener (PEM, client-auth NONE), schema.registry.url -> SR HA pair.

    destroy_rest_ips = join(",", [for n in local.kafka_rest_specs : n.vmnet11])
    destroy_ssh_user = var.kafka_node_user
  }

  depends_on = [null_resource.kafka_ecosystem_tls, null_resource.kafka_schema_registry]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser   = '${var.kafka_node_user}'
      $bootstrap = '${local.kafka_east_bootstrap}'
      $srUrls    = '${local.kafka_sr_urls}'
      $caFile    = '/etc/ssl/certs/kafka-ca.pem'
      $sshOpts   = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      $nodes = @'
${jsonencode(local.kafka_rest_specs)}
'@ | ConvertFrom-Json

      if ($nodes.Count -eq 0) {
        Write-Host "[kafka-rest] no enabled REST proxy node -- nothing to do"
        exit 0
      }

      foreach ($n in $nodes) {
        $hostName = $n.host
        $ip       = $n.vmnet11

        $props = @"
# Generated by role-overlay-rest.tf -- Phase 0.H.3. Do not edit by hand.
# Node: $hostName

# --- REST Proxy -> Kafka brokers (mTLS) ---
bootstrap.servers=$bootstrap
client.security.protocol=SSL
client.ssl.keystore.type=PEM
client.ssl.keystore.location=/etc/nexus-kafka/tls/keystore.pem
client.ssl.truststore.type=PEM
client.ssl.truststore.location=/etc/nexus-kafka/tls/truststore.pem
client.ssl.endpoint.identification.algorithm=https

# --- REST Proxy listener (HTTPS, server-side TLS; operator API) ---
listeners=https://0.0.0.0:8082
ssl.keystore.type=PEM
ssl.keystore.location=/etc/nexus-kafka/tls/keystore.pem
ssl.truststore.type=PEM
ssl.truststore.location=/etc/nexus-kafka/tls/truststore.pem
ssl.client.authentication=NONE

# --- REST Proxy -> Schema Registry HA pair ---
schema.registry.url=$srUrls
schema.registry.ssl.truststore.type=PEM
schema.registry.ssl.truststore.location=/etc/nexus-kafka/tls/truststore.pem
"@
        $propsB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($props -replace "`r`n","`n")))

        $stage = @"
set -euo pipefail
echo '$propsB64' | base64 -d | sudo tee /etc/nexus-kafka/kafka-rest.properties > /dev/null
sudo chown root:kafka /etc/nexus-kafka/kafka-rest.properties
sudo chmod 0640 /etc/nexus-kafka/kafka-rest.properties
sudo systemctl reset-failed kafka-rest.service 2>/dev/null || true
sudo systemctl enable kafka-rest.service
sudo systemctl restart kafka-rest.service
echo REST_START_OK
"@
        Write-Host "[kafka-rest $hostName] rendering config + starting kafka-rest.service"
        $stageOut = ($stage -replace "`r`n","`n") | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>&1 | Out-String
        if ($LASTEXITCODE -ne 0 -or $stageOut -notmatch 'REST_START_OK') {
          Write-Host $stageOut.Trim()
          throw "[kafka-rest $hostName] config render / service start failed (rc=$LASTEXITCODE)"
        }

        # Wait for the HTTPS listener + assert /topics returns the cluster's
        # topics (proves REST Proxy -> brokers mTLS works).
        Write-Host "[kafka-rest $hostName] waiting for https://$($ip):8082/topics ..."
        $deadline = (Get-Date).AddMinutes(5)
        $ready = $false
        while ((Get-Date) -lt $deadline) {
          $body = (ssh @sshOpts "$sshUser@$ip" "curl -s --cacert $caFile https://localhost:8082/topics 2>/dev/null" 2>&1 | Out-String).Trim()
          # A JSON array (even just "[]") means the listener + the broker
          # AdminClient call both succeeded.
          if ($body -match '^\[') { $ready = $true; break }
          Start-Sleep -Seconds 5
        }
        if (-not $ready) {
          $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u kafka-rest.service --no-pager -n 40" 2>&1 | Out-String)
          Write-Host $journal
          throw "[kafka-rest $hostName] REST listener not ready on :8082 within 5 min"
        }
        Write-Host "[kafka-rest $hostName] REST proxy live (HTTPS :8082; /topics answered over mTLS)"
      }

      Write-Host ""
      Write-Host "[kafka-rest] OK -- Confluent REST Proxy live on HTTPS :8082 (mTLS to kafka-east)"
    PWSH
  }

  # Destroy: stop + disable kafka-rest.service + remove the rendered config.
  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser = '${self.triggers.destroy_ssh_user}'
      $ips     = '${self.triggers.destroy_rest_ips}' -split ','
      $sshOpts = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      foreach ($ip in $ips) {
        if (-not $ip) { continue }
        Write-Host "[kafka-rest destroy] $${ip}: stopping kafka-rest.service + removing config"
        ssh @sshOpts "$sshUser@$ip" "sudo systemctl disable --now kafka-rest.service 2>/dev/null; sudo rm -f /etc/nexus-kafka/kafka-rest.properties" 2>$null
      }
      exit 0
    PWSH
  }
}
