/*
 * role-overlay-ksqldb.tf -- Phase 0.H.4
 *
 * Brings up the ksqlDB cluster (ksqldb-1/2). The two nodes share one
 * `ksql.service.id` + the same `bootstrap.servers` -> they form a single
 * cluster (shared state + command topic, pull-query routing across the
 * pair). Each is a Kafka client of the kafka-east brokers over mutual TLS,
 * serves its own HTTPS REST API on :8088, and is wired to the Schema
 * Registry HA pair.
 *
 * Pre-req: role-overlay-ecosystem-tls.tf rendered the PKI keystore on both
 * ksqlDB nodes; role-overlay-schema-registry.tf brought up the SR pair
 * (ksqlDB's ksql.schema.registry.url targets it).
 *
 * Steps (single count-gated resource, loops the pair in PowerShell):
 *   1. Render /etc/nexus-kafka/ksqldb-server.properties per node
 *      (ksql.advertised.listener = this node's VMnet10 HTTPS URL).
 *   2. Sequential start: ksqldb-1 first (it AdminClient-creates the command
 *      topic -- works with the brokers' auto.create.topics.enable=false;
 *      no ACLs), then ksqldb-2 joins the cluster.
 *   3. Verify: /info reports RUNNING on each node; /clusterStatus lists
 *      both nodes; a trivial KSQL statement (SHOW TOPICS;) succeeds.
 *
 * TLS notes (research-confirmed for Confluent 7.7):
 *   - ksqlDB's Kafka clients DO inherit top-level ssl.*; the ksql.streams.
 *     prefix scopes the Kafka mTLS block cleanly (decoupled from the REST
 *     listener).
 *   - the REST listener uses BARE ssl.* + ssl.client.authentication (this
 *     is the one place ksqlDB matches the Schema Registry pattern).
 *   - ksql.schema.registry.* needs only the truststore half -- the SR
 *     listener is client-auth NONE, so ksqlDB presents no client cert to it.
 *   - bootstrap.servers is the bare host:port form + ksql.streams.security.
 *     protocol=SSL (not the SSL:// scheme prefix).
 *
 * Selective ops: var.enable_ksqldb AND var.enable_ksqldb_config
 *                AND var.enable_ecosystem_tls.
 */

locals {
  kafka_ksqldb_specs = concat(
    var.enable_ksqldb && var.enable_ksqldb_1 ? [{ host = "ksqldb-1", vmnet10 = "192.168.10.97", vmnet11 = "192.168.70.97" }] : [],
    var.enable_ksqldb && var.enable_ksqldb_2 ? [{ host = "ksqldb-2", vmnet10 = "192.168.10.98", vmnet11 = "192.168.70.98" }] : [],
  )
}

resource "null_resource" "kafka_ksqldb" {
  count = var.enable_kafka_cluster && var.enable_ksqldb && var.enable_ksqldb_config && var.enable_ecosystem_tls && length(local.kafka_ksqldb_specs) > 0 ? 1 : 0

  triggers = {
    # Keyed only on this overlay's OWN inputs (node set / bootstrap / the SR
    # URL list). Ordering after the keystore render + the SR pair is handled
    # by depends_on -- NOT by kafka_ecosystem_tls / kafka_schema_registry id
    # triggers, which would needlessly re-run this overlay whenever those
    # upstreams re-run (the role-overlay-kafka-tls.tf va_ids lesson).
    nodes           = jsonencode(local.kafka_ksqldb_specs)
    bootstrap       = local.kafka_east_bootstrap_bare
    sr_urls         = local.kafka_sr_urls
    ksqldb_config_v = "1" # v1 = 2-node cluster (shared ksql.service.id + ksql.heartbeat.enable=true so /clusterStatus populates); ALL-PKCS#12 SSL (bare security.protocol=SSL + bare ssl.* for the ServiceContext AdminClient AND the REST listener, plus ksql.streams.* for the Streams clients, plus ksql.schema.registry.ssl.* -- KsqlRestConfig rejects PEM, so everything is PKCS#12); SR HA pair wired truststore-only; ksql.udf.enable.security.manager=false (Java 21 removed the SecurityManager); sequential start.

    destroy_ksqldb_ips = join(",", [for n in local.kafka_ksqldb_specs : n.vmnet11])
    destroy_ssh_user   = var.kafka_node_user
  }

  depends_on = [null_resource.kafka_ecosystem_tls, null_resource.kafka_schema_registry]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser   = '${var.kafka_node_user}'
      $bootstrap = '${local.kafka_east_bootstrap_bare}'
      $srUrls    = '${local.kafka_sr_urls}'
      $p12Pass   = '${var.kafka_keystore_password}'
      $caFile    = '/etc/ssl/certs/kafka-ca.pem'
      $sshOpts   = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      $nodes = @'
${jsonencode(local.kafka_ksqldb_specs)}
'@ | ConvertFrom-Json

      if ($nodes.Count -eq 0) {
        Write-Host "[ksqldb] no enabled ksqlDB nodes -- nothing to do"
        exit 0
      }

      # ─── Step 1: render config on each node ─────────────────────────────
      foreach ($n in $nodes) {
        $hostName = $n.host
        $ip       = $n.vmnet11
        $vmnet10  = $n.vmnet10

        $props = @"
# Generated by role-overlay-ksqldb.tf -- Phase 0.H.4. Do not edit by hand.
# Node: $hostName   advertised: $vmnet10

# --- cluster identity (ksql.service.id identical across the pair) ---
ksql.service.id=nexus_ksql_east_
bootstrap.servers=$bootstrap

# Bare security.protocol -- ksqlDB's ServiceContext AdminClient (used at
# startup for getKafkaClusterId) reads the BARE client config, not the
# ksql.streams.*-prefixed one. Without this it defaults to PLAINTEXT and the
# mTLS brokers disconnect it ("Bootstrap broker ... disconnected"). The bare
# ssl.* keystore/truststore below (shared with the REST listener) + this
# line give the bare Kafka client a complete SSL config.
security.protocol=SSL

# --- JVM compat: ksqlDB's UDF SecurityManager calls System.setSecurityManager(),
#     which throws UnsupportedOperationException on Java 17+ (the SecurityManager
#     is deprecated-for-removal). The kafka-node template runs Temurin JDK 21,
#     so disable the UDF security manager (lab: no untrusted UDFs run here). ---
ksql.udf.enable.security.manager=false

# --- Kafka mTLS connection (ksql.streams. prefix -> the Kafka clients) ---
# PKCS#12, NOT PEM: ksqlDB's bare ssl.* (the REST listener -- which MUST be
# PKCS#12 since KsqlRestConfig rejects PEM) is INHERITED by the embedded
# Kafka clients, and ssl.keystore.password bleeds in. A password is invalid
# with a PEM keystore ("SSL key store password cannot be specified with PEM
# format"), so the Kafka client must also be PKCS#12 to stay consistent with
# the bleed-through. The Kafka client supports PKCS#12 fine. (Connect has no
# such bleed -- its REST listener uses the isolated listeners.https. prefix.)
ksql.streams.security.protocol=SSL
ksql.streams.ssl.keystore.type=PKCS12
ksql.streams.ssl.keystore.location=/etc/nexus-kafka/tls/keystore.p12
ksql.streams.ssl.keystore.password=$p12Pass
ksql.streams.ssl.truststore.type=PKCS12
ksql.streams.ssl.truststore.location=/etc/nexus-kafka/tls/truststore.p12
ksql.streams.ssl.truststore.password=$p12Pass
ksql.streams.ssl.endpoint.identification.algorithm=https

# --- internal topic replication (default is 1 on CP -- must set 3) ---
ksql.internal.topic.replicas=3
ksql.streams.replication.factor=3

# --- REST API (HTTPS, server-side TLS; bare ssl.* keys -- operator API) ---
# PKCS#12 (NOT PEM) -- ksqlDB's KsqlRestConfig validates ssl.keystore.type
# against {JKS, PKCS12, BCFKS} and rejects PEM (unlike the ksql.streams.*
# Kafka client above, and unlike Schema Registry / REST Proxy rest-utils).
listeners=https://0.0.0.0:8088
ssl.keystore.type=PKCS12
ssl.keystore.location=/etc/nexus-kafka/tls/keystore.p12
ssl.keystore.password=$p12Pass
ssl.truststore.type=PKCS12
ssl.truststore.location=/etc/nexus-kafka/tls/truststore.p12
ssl.truststore.password=$p12Pass
ssl.client.authentication=NONE
ksql.advertised.listener=https://$${vmnet10}:8088

# Heartbeat agent -- drives /clusterStatus + pull-query routing across the
# pair. Defaults to false on CP, so /clusterStatus stays empty without it.
ksql.heartbeat.enable=true

# --- Schema Registry HA pair (truststore-only; SR listener is client-auth NONE) ---
# PKCS#12 truststore -- same KsqlRestConfig PEM-rejection applies to the
# ksql.schema.registry.ssl.* namespace.
ksql.schema.registry.url=$srUrls
ksql.schema.registry.ssl.truststore.type=PKCS12
ksql.schema.registry.ssl.truststore.location=/etc/nexus-kafka/tls/truststore.p12
ksql.schema.registry.ssl.truststore.password=$p12Pass
"@
        $propsB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($props -replace "`r`n","`n")))

        $stage = @"
set -euo pipefail
echo '$propsB64' | base64 -d | sudo tee /etc/nexus-kafka/ksqldb-server.properties > /dev/null
sudo chown root:kafka /etc/nexus-kafka/ksqldb-server.properties
sudo chmod 0640 /etc/nexus-kafka/ksqldb-server.properties
echo KSQL_STAGE_OK
"@
        Write-Host "[ksqldb $hostName] rendering ksqldb-server.properties"
        $stageOut = ($stage -replace "`r`n","`n") | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>&1 | Out-String
        if ($LASTEXITCODE -ne 0 -or $stageOut -notmatch 'KSQL_STAGE_OK') {
          Write-Host $stageOut.Trim()
          throw "[ksqldb $hostName] config render failed (rc=$LASTEXITCODE)"
        }
      }

      # ─── Step 2: sequential start (ksqldb-1 creates the command topic) ──
      foreach ($n in $nodes) {
        $hostName = $n.host
        $ip       = $n.vmnet11
        Write-Host "[ksqldb $hostName] enabling + starting ksqldb-server.service"
        $start = "sudo systemctl reset-failed ksqldb-server.service 2>/dev/null || true; sudo systemctl enable ksqldb-server.service && sudo systemctl restart ksqldb-server.service && echo KSQL_START_OK"
        $out = (ssh @sshOpts "$sshUser@$ip" $start 2>&1 | Out-String)
        if ($out -notmatch 'KSQL_START_OK') {
          throw "[ksqldb $hostName] ksqldb-server.service start failed -- $out"
        }

        Write-Host "[ksqldb $hostName] waiting for https://$($ip):8088/info ..."
        $deadline = (Get-Date).AddMinutes(8)
        $ready = $false
        while ((Get-Date) -lt $deadline) {
          $body = (ssh @sshOpts "$sshUser@$ip" "curl -s --cacert $caFile https://localhost:8088/info 2>/dev/null" 2>&1 | Out-String).Trim()
          if ($body -match 'KsqlServerInfo') { $ready = $true; break }
          Start-Sleep -Seconds 5
        }
        if (-not $ready) {
          $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u ksqldb-server.service --no-pager -n 40" 2>&1 | Out-String)
          Write-Host $journal
          throw "[ksqldb $hostName] REST API not ready on :8088 within 8 min"
        }
        Write-Host "[ksqldb $hostName] REST API live (HTTPS :8088)"
      }

      # ─── Step 3: verify -- cluster membership + a trivial KSQL statement ─
      $probeIp = $nodes[0].vmnet11

      # Deterministic proof the pair is one cluster: every node's /info
      # reports RUNNING on the SAME ksql.service.id AND the SAME backing Kafka
      # cluster id. ksqlDB clustering IS "same ksql.service.id + same
      # bootstrap.servers" -- the nodes then consume the one shared command
      # topic, so a DDL on either is seen by both. (NOT verified via
      # /clusterStatus: that endpoint is heartbeat-driven and only lists
      # PEERS once a persistent query exists -- a fresh, query-less cluster
      # always shows just the local node. ksql.heartbeat.enable=true is still
      # set for real pull-query routing once queries land.)
      $svcIds = @()
      foreach ($n in $nodes) {
        $info = (ssh @sshOpts "$sshUser@$($n.vmnet11)" "curl -s --cacert $caFile https://localhost:8088/info 2>/dev/null" 2>&1 | Out-String)
        if ($info -notmatch '"serverStatus"\s*:\s*"RUNNING"') {
          throw "[ksqldb] $($n.host): /info serverStatus is not RUNNING`n$info"
        }
        if ($info -notmatch '"ksqlServiceId"\s*:\s*"(nexus_ksql_east_)"') {
          throw "[ksqldb] $($n.host): /info ksqlServiceId is not nexus_ksql_east_`n$info"
        }
        if ($info -notmatch '"kafkaClusterId"\s*:\s*"([^"]+)"') {
          throw "[ksqldb] $($n.host): /info has no kafkaClusterId`n$info"
        }
        $svcIds += $Matches[1]
      }
      if (($svcIds | Select-Object -Unique).Count -ne 1) {
        throw "[ksqldb] nodes disagree on the backing Kafka cluster id: $($svcIds -join ', ')"
      }
      Write-Host "[ksqldb] all $($nodes.Count) node(s) RUNNING on ksql.service.id=nexus_ksql_east_, backing kafka cluster $($svcIds[0])"

      $ksqlBody = '{"ksql":"SHOW TOPICS;","streamsProperties":{}}'
      $showTopics = (ssh @sshOpts "$sshUser@$probeIp" "curl -s --cacert $caFile -X POST -H 'Content-Type: application/vnd.ksql.v1+json' --data '$ksqlBody' https://localhost:8088/ksql 2>/dev/null" 2>&1 | Out-String)
      if ($showTopics -notmatch '"topics"') {
        throw "[ksqldb] SHOW TOPICS; via the /ksql endpoint did not return a topics list`n$showTopics"
      }
      Write-Host "[ksqldb] SHOW TOPICS; round-trip OK via the /ksql endpoint"

      Write-Host ""
      Write-Host "[ksqldb] OK -- ksqlDB cluster live on HTTPS :8088 (mTLS to kafka-east; SR HA pair wired)"
    PWSH
  }

  # Destroy: stop + disable ksqldb-server.service + remove the rendered config.
  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser = '${self.triggers.destroy_ssh_user}'
      $ips     = '${self.triggers.destroy_ksqldb_ips}' -split ','
      $sshOpts = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      foreach ($ip in $ips) {
        if (-not $ip) { continue }
        Write-Host "[ksqldb destroy] $${ip}: stopping ksqldb-server.service + removing config"
        ssh @sshOpts "$sshUser@$ip" "sudo systemctl disable --now ksqldb-server.service 2>/dev/null; sudo rm -f /etc/nexus-kafka/ksqldb-server.properties" 2>$null
      }
      exit 0
    PWSH
  }
}
