/*
 * role-overlay-kafka-tls.tf -- Phase 0.H.2 -- Kafka broker mTLS
 *
 * Flips both KRaft clusters from PLAINTEXT (0.H.1) to mutual TLS. Per-broker
 * leaf certs are issued from Vault PKI's pki_int/roles/kafka-broker (created
 * security-side in 0.H.2 setup) by each node's Vault Agent
 * (role-overlay-kafka-vault-agents.tf). All three listeners go SSL:
 *
 *   - client listener      SSL://0.0.0.0:9092      (also the inter-broker
 *                          listener -- inter.broker.listener.name=SSL)
 *   - controller listener  CONTROLLER://<vmnet10>:9093  (SSL protocol)
 *
 * ssl.client.auth=required makes it MUTUAL TLS everywhere: inter-broker
 * replication, the controller quorum, AND external clients must all present
 * a client cert. There is no "operator API without a client cert" carve-out
 * (contrast Consul's https.verify_incoming=false) because every Kafka client
 * in the lab runs FROM a broker and can use that broker's own keystore as
 * its client identity (the kafka-broker PKI role has client_flag=true). The
 * /etc/nexus-kafka/client-ssl.properties dropped here points the CLI tools
 * at exactly that keystore.
 *
 * Ports are UNCHANGED from 0.H.1 (9092 + 9093) -- only the wire protocol
 * flips -- so role-overlay-nftables-backplane.tf needs no change.
 *
 * Keystore format: Kafka 3.8's native PEM type (ssl.keystore.type=PEM). The
 * Vault Agent renders one bundle.pem (leaf + key + issuing CA); the
 * kafka-tls-split.sh post-render command splits it into keystore.pem (key +
 * leaf + intermediate, so the broker presents the full chain) and
 * truststore.pem (the intermediate CA alone). No JKS, no keytool, no
 * keystore password -- closest analogue to the consul/nomad PEM pattern.
 *
 * --- Choreography (single count-gated resource, loops hosts in PowerShell) -
 *
 *   Phase 1 (per-node, SEQUENTIAL, does NOT restart kafka.service):
 *     install kafka-tls-split.sh + drop the per-host Vault Agent PKI
 *     template (60-template-kafka-tls.hcl) + restart nexus-vault-agent +
 *     wait for the cert bundle to render + run the split script + drop the
 *     mTLS server.properties + client-ssl.properties. kafka.service keeps
 *     running on PLAINTEXT (old config still in memory) until Phase 2.
 *     Sequential is safe -- nothing here touches the running broker.
 *
 *   Phase 2 (per-cluster, PARALLEL-within-cluster big-bang restart):
 *     systemctl restart kafka.service on all 3 nodes of a cluster
 *     simultaneously, then wait for the KRaft quorum to re-form over SSL.
 *     A TLS wire-format flip MUST be a parallel big-bang -- a sequential
 *     rolling restart would isolate the first node (SSL-only) from peers
 *     still on PLAINTEXT and the controller quorum can't elect during the
 *     gap (the nomad-tls / consul-tls lesson; KRaft's controller quorum is
 *     a Raft group exactly like Consul/Nomad's). The two clusters are
 *     independent, so they flip one after the other -- west stays up while
 *     east converges -- but the 3 nodes WITHIN a cluster always go together.
 *
 *   Phase 3 (verification): per cluster, assert the KRaft quorum has a
 *     leader + 3 voters over SSL and an RF=3 produce/consume round-trip
 *     succeeds over mTLS (the 0.H.2 exit gate).
 *
 * Idempotency: the Vault Agent caches pkiCert results, so the split script
 * is invoked manually after each render (a restart with an unchanged cert
 * would not fire the command-on-render trigger). Re-applying with the
 * cluster already TLS-enabled is a clean no-op-fast (Phase 2 restart still
 * succeeds).
 *
 * Selective ops: var.enable_kafka_tls AND var.enable_kafka_vault_agents.
 */

locals {
  # mTLS server.properties per enabled broker (keyed by VMnet11 IP). This
  # overlay OWNS the TLS variant; role-overlay-broker-config.tf owns the
  # 0.H.1 PLAINTEXT variant. On a full apply broker-config renders PLAINTEXT
  # first, 0.H.1's kraft-format brings the cluster up, then this overlay
  # re-renders SSL + restarts.
  kafka_tls_props_mtls = {
    for b in local.kafka_enabled_brokers : b.vmnet11 => join("\n", [
      "# Generated by role-overlay-kafka-tls.tf -- Phase 0.H.2 mTLS. Do not edit by hand.",
      "# Cluster: ${b.cluster}   node.id: ${b.node_id}   backplane: ${b.vmnet10}",
      "process.roles=broker,controller",
      "node.id=${b.node_id}",
      "controller.quorum.voters=${b.quorum}",
      "",
      "listeners=SSL://0.0.0.0:9092,CONTROLLER://${b.vmnet10}:9093",
      "advertised.listeners=SSL://${b.vmnet10}:9092",
      "controller.listener.names=CONTROLLER",
      "inter.broker.listener.name=SSL",
      "listener.security.protocol.map=SSL:SSL,CONTROLLER:SSL",
      "",
      "# --- Phase 0.H.2 mTLS: PEM keystore/truststore from Vault PKI ---",
      "ssl.keystore.type=PEM",
      "ssl.keystore.location=/etc/nexus-kafka/tls/keystore.pem",
      "ssl.truststore.type=PEM",
      "ssl.truststore.location=/etc/nexus-kafka/tls/truststore.pem",
      "ssl.client.auth=required",
      "ssl.endpoint.identification.algorithm=https",
      "",
      "log.dirs=/var/lib/kafka/data",
      "num.partitions=3",
      "default.replication.factor=3",
      "offsets.topic.replication.factor=3",
      "transaction.state.log.replication.factor=3",
      "transaction.state.log.min.isr=2",
      "min.insync.replicas=2",
      "auto.create.topics.enable=false",
      "",
    ])
  }

  # PLAINTEXT server.properties per enabled broker -- frozen into triggers so
  # the destroy provisioner can restore the cluster to a working 0.H.1 state
  # (matches role-overlay-broker-config.tf's render).
  kafka_tls_props_plaintext = {
    for b in local.kafka_enabled_brokers : b.vmnet11 => join("\n", [
      "# Restored by role-overlay-kafka-tls.tf destroy -- Phase 0.H.1 PLAINTEXT fallback.",
      "# Cluster: ${b.cluster}   node.id: ${b.node_id}   backplane: ${b.vmnet10}",
      "process.roles=broker,controller",
      "node.id=${b.node_id}",
      "controller.quorum.voters=${b.quorum}",
      "",
      "listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://${b.vmnet10}:9093",
      "advertised.listeners=PLAINTEXT://${b.vmnet10}:9092",
      "controller.listener.names=CONTROLLER",
      "inter.broker.listener.name=PLAINTEXT",
      "listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT",
      "",
      "log.dirs=/var/lib/kafka/data",
      "num.partitions=3",
      "default.replication.factor=3",
      "offsets.topic.replication.factor=3",
      "transaction.state.log.replication.factor=3",
      "transaction.state.log.min.isr=2",
      "min.insync.replicas=2",
      "auto.create.topics.enable=false",
      "",
    ])
  }
}

resource "null_resource" "kafka_tls" {
  count = var.enable_kafka_cluster && var.enable_kafka_tls && var.enable_kafka_vault_agents ? 1 : 0

  triggers = {
    # Re-run only when the broker SET changes (broker added/removed) or the
    # PKI role / overlay version changes. Deliberately NOT keyed on the Vault
    # Agent resource ids: those rotate on every security-env apply (secret-id
    # rotation) but a rotation does NOT change the broker's cert, so keying on
    # them would needlessly re-run the whole mTLS flip (= a cluster restart)
    # on every cycle. Ordering is handled by depends_on; the
    # kafka_vault_agent destroy provisioner is surgical, so 60-template-
    # kafka-tls.hcl survives an agent re-install -- this overlay does not need
    # to re-run to restore it.
    pki_role_name = var.vault_pki_kafka_role_name
    brokers       = jsonencode(local.kafka_enabled_brokers)
    kafka_tls_v   = "4" # v4 (0.H.4 recovery) = forced re-run to re-render the SSL server.properties that role-overlay-broker-config.tf clobbered back to PLAINTEXT when the nftables->broker-config id-trigger cascade re-ran it (the cascade is fixed in broker-config v2 / kraft-format v2). Content-identical to v3 -- this bump just re-asserts the mTLS server.properties. v3 (0.H.3) = dropped the `va_ids` trigger -- it re-ran the broker mTLS flip on every security-env re-apply (secret-id rotation churned the Vault Agent ids); paired with the kafka_vault_agent surgical-destroy fix so the TLS template survives agent re-installs. v2 = (a) kafka-tls-split.sh converts the Vault-PKI RSA key PKCS#1->PKCS#8 (`openssl pkcs8 -topk8`); (b) Phase 2 restart does `systemctl reset-failed` first. v1 = original.

    # Frozen for the destroy provisioner.
    destroy_broker_ips      = join(",", [for b in local.kafka_enabled_brokers : b.vmnet11])
    destroy_plaintext_props = jsonencode(local.kafka_tls_props_plaintext)
    destroy_ssh_user        = var.kafka_node_user
  }

  depends_on = [null_resource.kafka_vault_agent]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser = '${var.kafka_node_user}'
      $pkiRole = '${var.vault_pki_kafka_role_name}'
      $timeout = ${var.kafka_cluster_timeout_minutes}
      $kafka   = '/opt/kafka/bin'
      $clientCfg = '/etc/nexus-kafka/client-ssl.properties'
      $sshOpts = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      # Terraform-computed tables (JSON -> PS objects).
      $brokers = @'
${jsonencode(local.kafka_enabled_brokers)}
'@ | ConvertFrom-Json

      $propsMtls = @'
${jsonencode(local.kafka_tls_props_mtls)}
'@ | ConvertFrom-Json

      if ($brokers.Count -eq 0) {
        Write-Host "[kafka-tls] no enabled brokers -- nothing to do"
        exit 0
      }

      # ─── Common artifact: the bundle-split post-render script ────────────
      # Single-quoted here-string -- everything literal, no PS interpolation.
      $splitScript = @'
#!/bin/bash
set -euo pipefail
BUNDLE=/etc/nexus-kafka/tls/bundle.pem
DEST=/etc/nexus-kafka/tls
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

# Split bundle.pem into per-PEM-block files. awk increments on each BEGIN.
awk -v tmp="$TMP" '
  /-----BEGIN/ { n++; file=tmp"/block-"n }
  { if (n>0) print > file }
' "$BUNDLE"

LEAF=""
KEY=""
CA=""
for f in "$TMP"/block-*; do
  hdr=$(head -1 "$f")
  case "$hdr" in
    *"PRIVATE KEY"*)
      KEY=$f
      ;;
    *"BEGIN CERTIFICATE"*)
      if [ -z "$LEAF" ]; then LEAF=$f; else CA=$f; fi
      ;;
  esac
done

if [ -z "$LEAF" ] || [ -z "$KEY" ] || [ -z "$CA" ]; then
  echo "[kafka-tls-split] ERROR: bundle missing one of leaf/key/ca" >&2
  ls -la "$TMP" >&2
  exit 1
fi

# Vault PKI issues RSA keys in PKCS#1 (-----BEGIN RSA PRIVATE KEY-----), but
# Kafka's PEM keystore parser is Java, which only accepts PKCS#8
# (-----BEGIN PRIVATE KEY-----). A PKCS#1 key fails broker startup with
# "java.security.InvalidKeyException: algid parse error, not a sequence".
# Convert to PKCS#8 (idempotent: -topk8 on an already-PKCS#8 key re-emits it).
# Consul/Nomad don't need this -- Go's crypto/tls reads both formats.
openssl pkcs8 -topk8 -nocrypt -in "$KEY" -out "$TMP/key-pkcs8.pem"

# keystore.pem = PKCS#8 private key + leaf + intermediate (broker presents the
# FULL chain on the TLS handshake -- the 0.E.4e full-chain lesson).
# truststore.pem = the intermediate CA alone (the trust anchor every mTLS peer
# verifies against).
cat "$TMP/key-pkcs8.pem" "$LEAF" "$CA" > "$TMP/keystore.pem"
cp "$CA" "$TMP/truststore.pem"

install -m 0640 -o root -g kafka "$TMP/keystore.pem"   "$DEST/keystore.pem"
install -m 0644 -o root -g kafka "$TMP/truststore.pem" "$DEST/truststore.pem"

# Operator-readable copy of the CA. /etc/nexus-kafka/ is 0750 root:kafka so
# nexusadmin cannot traverse it; a world-readable copy lets a CLI run as
# nexusadmin still chain-verify if needed.
install -m 0644 -o root -g root "$CA" /etc/ssl/certs/kafka-ca.pem

echo "[kafka-tls-split] $(date -u +%FT%TZ) bundle split: keystore.pem + truststore.pem (+ /etc/ssl/certs/kafka-ca.pem)"
'@

      # Common artifact: the client SSL config the CLI tools use. The smoke
      # gate + operator run the kafka tools FROM a broker (via sudo, since
      # keystore.pem is 0640 root:kafka) pointing --command-config here.
      $clientSslConfig = @'
# /etc/nexus-kafka/client-ssl.properties -- Phase 0.H.2.
# Kafka CLI client config for mTLS. The broker's own PKI keystore doubles as
# the client identity (the kafka-broker PKI role has client_flag=true).
security.protocol=SSL
ssl.keystore.type=PEM
ssl.keystore.location=/etc/nexus-kafka/tls/keystore.pem
ssl.truststore.type=PEM
ssl.truststore.location=/etc/nexus-kafka/tls/truststore.pem
ssl.endpoint.identification.algorithm=https
'@

      $splitB64     = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($splitScript     -replace "`r`n","`n")))
      $clientSslB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($clientSslConfig -replace "`r`n","`n")))

      # ─── Phase 1 (per-node, sequential, no kafka restart) ───────────────
      foreach ($b in $brokers) {
        $hostName = "kafka-$($b.cluster)-$($b.node_id)"
        $ip       = $b.vmnet11
        $cn       = "$hostName.kafka.nexus.lab"
        $altNames = "$hostName,$hostName.nexus.lab,$hostName.kafka.nexus.lab,localhost"
        $ipSans   = "$($b.vmnet10),$($b.vmnet11),127.0.0.1"

        Write-Host ""
        Write-Host "[kafka-tls $hostName] Phase 1 -- cert render + mTLS config drop"

        # Per-host Vault Agent PKI template. Double-quoted here-string so
        # $pkiRole/$cn/$altNames/$ipSans interpolate; HCL quotes inside are
        # backtick-escaped per memory/feedback_terraform_heredoc_powershell.md.
        $vaultAgentTemplate = @"
# 60-template-kafka-tls.hcl -- Phase 0.H.2 (rendered for $hostName).
# Issues a Kafka broker TLS leaf from pki_int/roles/$pkiRole and writes one
# bundle file; the post-render command splits it into keystore + truststore.

template {
  contents = <<EOT
{{- with pkiCert `"pki_int/issue/$pkiRole`" `"common_name=$cn`" `"alt_names=$altNames`" `"ip_sans=$ipSans`" `"ttl=2160h`" }}
{{ .Cert }}
{{ .Key }}
{{ .CA }}
{{- end }}
EOT

  destination     = "/etc/nexus-kafka/tls/bundle.pem"
  perms           = "0640"
  user            = "root"
  group           = "kafka"
  command         = "/usr/local/sbin/kafka-tls-split.sh"
  command_timeout = "30s"
}
"@
        $vaB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($vaultAgentTemplate -replace "`r`n","`n")))

        # This node's mTLS server.properties (Terraform-rendered).
        $propsB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes((($propsMtls.$ip) -replace "`r`n","`n")))

        # stage1: install split script + VA template, restart vault-agent,
        # wait for the bundle, run the split, then drop server.properties +
        # client-ssl.properties. Piped to ssh stdin + `bash -s` (the 4 nested
        # base64 blobs push well past the ~6KB ssh.exe argv cliff).
        $stage1 = @"
set -euo pipefail
sudo mkdir -p /etc/nexus-kafka/tls
sudo chown root:kafka /etc/nexus-kafka/tls
sudo chmod 0750 /etc/nexus-kafka/tls

echo '$splitB64' | base64 -d | sudo tee /usr/local/sbin/kafka-tls-split.sh > /dev/null
sudo chown root:root /usr/local/sbin/kafka-tls-split.sh
sudo chmod 0755 /usr/local/sbin/kafka-tls-split.sh

echo '$vaB64' | base64 -d | sudo tee /etc/vault-agent/60-template-kafka-tls.hcl > /dev/null
sudo chown root:root /etc/vault-agent/60-template-kafka-tls.hcl
sudo chmod 0644 /etc/vault-agent/60-template-kafka-tls.hcl

sudo systemctl restart nexus-vault-agent.service

# Wait for bundle.pem, then run the split manually -- pkiCert results are
# CACHED by the Vault Agent, so a restart with an unchanged cert does NOT
# fire the command-on-render trigger. Manual invocation is idempotent.
for i in 1 2 3 4 5 6 7 8 9 10; do
  sudo test -s /etc/nexus-kafka/tls/bundle.pem && break
  sleep 2
done
if ! sudo test -s /etc/nexus-kafka/tls/bundle.pem; then
  echo "[stage1] ERROR: bundle.pem not rendered within 20s after vault-agent restart" >&2
  sudo journalctl -u nexus-vault-agent.service --no-pager -n 20 >&2
  exit 1
fi
sudo /usr/local/sbin/kafka-tls-split.sh

echo '$propsB64' | base64 -d | sudo tee /etc/nexus-kafka/server.properties > /dev/null
sudo chown root:kafka /etc/nexus-kafka/server.properties
sudo chmod 0640 /etc/nexus-kafka/server.properties

echo '$clientSslB64' | base64 -d | sudo tee /etc/nexus-kafka/client-ssl.properties > /dev/null
sudo chown root:kafka /etc/nexus-kafka/client-ssl.properties
sudo chmod 0644 /etc/nexus-kafka/client-ssl.properties
echo STAGE1_OK
"@
        $stage1Lf  = $stage1 -replace "`r`n", "`n"
        $stage1Out = $stage1Lf | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>&1 | Out-String
        if ($LASTEXITCODE -ne 0 -or $stage1Out -notmatch 'STAGE1_OK') {
          Write-Host $stage1Out.Trim()
          throw "[kafka-tls $hostName] phase1 (cert render + config drop) failed (rc=$LASTEXITCODE)"
        }

        # Wait for the cert files + verify the CN.
        $deadline = (Get-Date).AddSeconds(60)
        $rendered = $false
        while ((Get-Date) -lt $deadline) {
          $check = (ssh @sshOpts "$sshUser@$ip" "sudo test -s /etc/nexus-kafka/tls/keystore.pem && sudo test -s /etc/nexus-kafka/tls/truststore.pem && sudo openssl x509 -in /etc/nexus-kafka/tls/keystore.pem -noout -subject 2>/dev/null | grep -q '$cn' && echo OK" 2>&1 | Out-String).Trim()
          if ($check -match 'OK') { $rendered = $true; break }
          Start-Sleep -Seconds 3
        }
        if (-not $rendered) {
          $journal = (ssh @sshOpts "$sshUser@$ip" "sudo journalctl -u nexus-vault-agent.service --no-pager -n 40" 2>&1 | Out-String)
          Write-Host $journal
          throw "[kafka-tls $hostName] cert files not rendered (CN=$cn) within 60s"
        }
        Write-Host "[kafka-tls $hostName] cert rendered (CN=$cn); mTLS server.properties staged"
      }

      Write-Host ""
      Write-Host "[kafka-tls] Phase 1 complete -- all $($brokers.Count) broker(s) have certs + mTLS config staged."

      # ─── Phase 2 (per-cluster, parallel-within-cluster big-bang restart) ─
      $clusterNames = ($brokers | ForEach-Object { $_.cluster } | Select-Object -Unique)
      foreach ($cl in $clusterNames) {
        $clNodes = @($brokers | Where-Object { $_.cluster -eq $cl })
        Write-Host ""
        Write-Host "[kafka-tls] Phase 2 -- big-bang restart of kafka-$cl ($($clNodes.Count) nodes, parallel)..."

        $restartErrors = $clNodes | ForEach-Object -ThrottleLimit 3 -Parallel {
          $node    = $_
          $sshUser = $using:sshUser
          $sshOpts = $using:sshOpts
          # reset-failed first: a prior failed apply can leave kafka.service
          # start-limited (StartLimitBurst=15), which makes a plain restart
          # fail with "start request repeated too quickly".
          $out = ssh @sshOpts "$sshUser@$($node.vmnet11)" "sudo systemctl reset-failed kafka.service 2>/dev/null; sudo systemctl restart kafka.service" 2>&1 | Out-String
          if ($LASTEXITCODE -ne 0) {
            return "[kafka-$($node.cluster)-$($node.node_id)] restart failed (rc=$LASTEXITCODE): $($out.Trim())"
          }
          return $null
        } | Where-Object { $_ -ne $null }

        if ($restartErrors.Count -gt 0) {
          $restartErrors | ForEach-Object { Write-Host $_ -ForegroundColor Red }
          throw "[kafka-tls] phase2 restart of kafka-$cl failed on $($restartErrors.Count) node(s)"
        }

        # Parallel wait: kafka.service active + KRaft quorum re-formed over
        # SSL (the metadata-quorum probe uses the client mTLS keystore, so a
        # green result proves the SSL listener + mTLS handshake both work).
        $waitErrors = $clNodes | ForEach-Object -ThrottleLimit 3 -Parallel {
          $node      = $_
          $sshUser   = $using:sshUser
          $sshOpts   = $using:sshOpts
          $kafka     = $using:kafka
          $clientCfg = $using:clientCfg
          $timeout   = $using:timeout
          $deadline  = (Get-Date).AddMinutes($timeout)
          while ((Get-Date) -lt $deadline) {
            $active = (ssh @sshOpts "$sshUser@$($node.vmnet11)" "systemctl is-active kafka.service" 2>&1 | Out-String).Trim()
            if ($active -eq 'active') {
              $status = (ssh @sshOpts "$sshUser@$($node.vmnet11)" "sudo $kafka/kafka-metadata-quorum.sh --bootstrap-server localhost:9092 --command-config $clientCfg describe --status 2>/dev/null" 2>&1 | Out-String)
              if ($status -match 'LeaderId:\s*\d+') { return $null }
            }
            Start-Sleep -Seconds 10
          }
          $journal = (ssh @sshOpts "$sshUser@$($node.vmnet11)" "sudo journalctl -u kafka.service --no-pager -n 30" 2>&1 | Out-String)
          return "[kafka-$($node.cluster)-$($node.node_id)] kafka.service / KRaft-over-SSL not ready within $timeout min; journal:`n$journal"
        } | Where-Object { $_ -ne $null }

        if ($waitErrors.Count -gt 0) {
          $waitErrors | ForEach-Object { Write-Host $_ -ForegroundColor Red }
          throw "[kafka-tls] phase2 wait (kafka-$cl SSL ready) failed on $($waitErrors.Count) node(s)"
        }
        Write-Host "[kafka-tls] Phase 2 -- kafka-$cl restarted; KRaft quorum re-formed over SSL."
      }

      # ─── Phase 3 (verification: quorum + RF=3 round-trip over mTLS) ──────
      Write-Host ""
      Write-Host "[kafka-tls] Phase 3 -- verifying cluster shape + RF=3 round-trip over mTLS..."
      Start-Sleep -Seconds 5

      foreach ($cl in $clusterNames) {
        $clNodes = @($brokers | Where-Object { $_.cluster -eq $cl })
        $probeIp = $clNodes[0].vmnet11

        $status = (ssh @sshOpts "$sshUser@$probeIp" "sudo $kafka/kafka-metadata-quorum.sh --bootstrap-server localhost:9092 --command-config $clientCfg describe --status 2>/dev/null" 2>&1 | Out-String)
        if ($status -notmatch 'LeaderId:\s*\d+') {
          throw "[kafka-tls] kafka-$cl : KRaft quorum has no leader over SSL`n$status"
        }
        if ($status -notmatch 'CurrentVoters:.*\d+.*\d+.*\d+') {
          throw "[kafka-tls] kafka-$cl : KRaft quorum does not show 3 voters over SSL`n$status"
        }
        Write-Host "[kafka-tls] kafka-$cl : KRaft quorum has a leader + 3 voters (over mTLS)"

        # RF=3 produce/consume round-trip over mTLS (the 0.H.2 exit gate).
        $token = "tls-rt-$(Get-Random)-$([DateTimeOffset]::UtcNow.ToUnixTimeSeconds())"
        $topic = "nexus-smoke-tls-$cl"
        $rt = @"
set -e
sudo $kafka/kafka-topics.sh --bootstrap-server localhost:9092 --command-config $clientCfg --create --if-not-exists --topic $topic --partitions 3 --replication-factor 3
echo '$token' | sudo $kafka/kafka-console-producer.sh --bootstrap-server localhost:9092 --producer.config $clientCfg --topic $topic
sudo $kafka/kafka-console-consumer.sh --bootstrap-server localhost:9092 --consumer.config $clientCfg --topic $topic --from-beginning --timeout-ms 15000 2>/dev/null
"@
        $rtOut = (ssh @sshOpts "$sshUser@$probeIp" $rt 2>&1 | Out-String)
        if ($rtOut -notmatch [regex]::Escape($token)) {
          throw "[kafka-tls] kafka-$cl : RF=3 mTLS round-trip failed -- token '$token' not seen`n$rtOut"
        }
        Write-Host "[kafka-tls] kafka-$cl : RF=3 produce/consume round-trip OK over mTLS"
      }

      Write-Host ""
      Write-Host "[kafka-tls] OK -- both KRaft clusters on mutual TLS (0.H.2 exit gate met)"
    PWSH
  }

  # Destroy: restore the PLAINTEXT server.properties (frozen into triggers),
  # remove the TLS artifacts + Vault Agent template, restart vault-agent +
  # kafka so the cluster falls back to a working 0.H.1 state.
  provisioner "local-exec" {
    when        = destroy
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser = '${self.triggers.destroy_ssh_user}'
      $ips     = '${self.triggers.destroy_broker_ips}' -split ','
      $sshOpts = @('-o','ConnectTimeout=5','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')

      $propsPlain = @'
${self.triggers.destroy_plaintext_props}
'@ | ConvertFrom-Json

      foreach ($ip in $ips) {
        if (-not $ip) { continue }
        Write-Host "[kafka-tls destroy] $${ip}: restoring PLAINTEXT server.properties + removing TLS artifacts"
        $propsB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes((($propsPlain.$ip) -replace "`r`n","`n")))
        $remote = @"
set -euo pipefail
echo '$propsB64' | base64 -d | sudo tee /etc/nexus-kafka/server.properties > /dev/null
sudo chown root:kafka /etc/nexus-kafka/server.properties
sudo chmod 0640 /etc/nexus-kafka/server.properties
sudo rm -f /etc/vault-agent/60-template-kafka-tls.hcl /usr/local/sbin/kafka-tls-split.sh /etc/nexus-kafka/tls/bundle.pem /etc/nexus-kafka/tls/keystore.pem /etc/nexus-kafka/tls/truststore.pem /etc/nexus-kafka/client-ssl.properties /etc/ssl/certs/kafka-ca.pem
sudo systemctl restart nexus-vault-agent.service 2>/dev/null || true
sudo systemctl restart kafka.service
"@
        ($remote -replace "`r`n","`n") | ssh @sshOpts "$sshUser@$ip" "tr -d '\r' | bash -s" 2>$null
      }
      exit 0
    PWSH
  }
}
